// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prxwebmiwnxvntfipzth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByeHdlYm1pd254dm50ZmlwenRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODg1MDksImV4cCI6MjA2ODE2NDUwOX0.7wtBcJI5JnbGue-iqw003VMsUApabDpz1_2adkerJmM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});